In [1]:
import pandas as pd
import numpy as np
from langdetect import detect

In [2]:
codex_df = pd.read_csv(r'C:\Users\chery\Desktop\python_proj\reviews.csv')
codex_df=codex_df.dropna()
codex_df

,Hotel Name,Content,Rating,Date of stay
1,Carlton City Hotel Singapore (SG Clean),The location is very good for train and shopping,10.0,2-Oct-22
3,Carlton City Hotel Singapore (SG Clean),I had a restful stay and staff was friendly.,8.0,19-Sep-22
5,Carlton City Hotel Singapore (SG Clean),Service was excellent but when I tried to orde...,10.0,15-Sep-22
7,Carlton City Hotel Singapore (SG Clean),"Prime service, room, amenities, and location. ...",10.0,13-Sep-22
9,Carlton City Hotel Singapore (SG Clean),The hotel was very nice and clean. Would defin...,10.0,5-Sep-22
...,...,...,...,...
11927,Orchard Hotel Singapore (SG Clean),Room and staff are great.\r\nBreakfast wasn't ...,8.0,26-Jul-20
11929,Orchard Hotel Singapore (SG Clean),"Excellent stay, excellent service, great staff.",10.0,20-Jul-20
11933,Orchard Hotel Singapore (SG Clean),It’s at the tail end of Orchard road need to ...,6.0,16-Apr-20
11935,Orchard Hotel Singapore (SG Clean),A big Thank You to Juan for all the help! I hi...,10.0,27-Mar-20
11937,Orchard Hotel Singapore (SG Clean),Appreciate the air purifier that was placed ri...,10.0,25-Mar-20

In [3]:
codex_df=codex_df.drop_duplicates()

In [4]:
codex_df['Content'].replace('', np.nan)

1         The location is very good for train and shopping
3             I had a restful stay and staff was friendly.
5        Service was excellent but when I tried to orde...
7        Prime service, room, amenities, and location. ...
9        The hotel was very nice and clean. Would defin...
                               ...
11927    Room and staff are great.\r\nBreakfast wasn't ...
11929      Excellent stay, excellent service, great staff.
11933    It’s at the tail end of Orchard road  need to ...
11935    A big Thank You to Juan for all the help! I hi...
11937    Appreciate the air purifier that was placed ri...
Name: Content, Length: 3689, dtype: object

In [5]:
codex_df.dropna(subset=['Content'], inplace=True)

C:\Users\chery\anaconda3\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [6]:
codex_df=codex_df[codex_df.Content.map(lambda x: x.isascii())]

In [7]:
codex_df

,Hotel Name,Content,Rating,Date of stay
1,Carlton City Hotel Singapore (SG Clean),The location is very good for train and shopping,10.0,2-Oct-22
3,Carlton City Hotel Singapore (SG Clean),I had a restful stay and staff was friendly.,8.0,19-Sep-22
5,Carlton City Hotel Singapore (SG Clean),Service was excellent but when I tried to orde...,10.0,15-Sep-22
7,Carlton City Hotel Singapore (SG Clean),"Prime service, room, amenities, and location. ...",10.0,13-Sep-22
9,Carlton City Hotel Singapore (SG Clean),The hotel was very nice and clean. Would defin...,10.0,5-Sep-22
...,...,...,...,...
11921,Orchard Hotel Singapore (SG Clean),Room is big and clean. Just there are no hair ...,6.0,10-Aug-20
11927,Orchard Hotel Singapore (SG Clean),Room and staff are great.\r\nBreakfast wasn't ...,8.0,26-Jul-20
11929,Orchard Hotel Singapore (SG Clean),"Excellent stay, excellent service, great staff.",10.0,20-Jul-20
11935,Orchard Hotel Singapore (SG Clean),A big Thank You to Juan for all the help! I hi...,10.0,27-Mar-20
11937,Orchard Hotel Singapore (SG Clean),Appreciate the air purifier that was placed ri...,10.0,25-Mar-20

In [8]:
verno_df=pd.read_csv(r'C:\Users\chery\Desktop\python_proj\TAHotelsReviews.csv')

verno_df

,Hotel Name,Title,Content,Rating,Date of stay
0,Marina Bay Sands,Fantastic Hotel - A Must Stay,It was my first time to Singapore which was fo...,10,September 2022
1,Marina Bay Sands,MBS a luxurious destination,"We are a family of 6 ( my 85 yearold father, 7...",10,July 2022
2,Marina Bay Sands,Debit card charged without refund after check ...,Stay from 05 sep to 08 sep 2022. Hotel request...,2,September 2022
3,Marina Bay Sands,Best View of Singapore,Marina Bay sands is a must visit place for any...,10,September 2022
4,Marina Bay Sands,The New Icon of Singapore,"One of the best hotels in Singapore, the garde...",10,July 2022
...,...,...,...,...,...
5995,Carlton Hotel Singapore,Good stay!,Worth for the money you spend and the location...,8,May 2019
5996,Carlton Hotel Singapore,"Amazing Hotel, wonderful staff",We had a wonderful stay at the Carlton. We had...,10,May 2019
5997,Carlton Hotel Singapore,Expansive for the service provided and not at ...,Very badly surprised by this hotel which is no...,4,May 2019
5998,Carlton Hotel Singapore,Great Hotel and Location,This hotel was awesome. We had a great stay. C...,10,May 2019
5999,Carlton Hotel Singapore,"Great staff, Massive varied breakfast, lovely ...",Ive stayed in lots of hotels in Singapore and ...,10,May 2019

In [9]:
verno_df=verno_df.drop_duplicates()
verno_df=verno_df[['Hotel Name', 'Content', 'Rating', 'Date of stay']]
verno_df

,Hotel Name,Content,Rating,Date of stay
0,Marina Bay Sands,It was my first time to Singapore which was fo...,10,September 2022
1,Marina Bay Sands,"We are a family of 6 ( my 85 yearold father, 7...",10,July 2022
2,Marina Bay Sands,Stay from 05 sep to 08 sep 2022. Hotel request...,2,September 2022
3,Marina Bay Sands,Marina Bay sands is a must visit place for any...,10,September 2022
4,Marina Bay Sands,"One of the best hotels in Singapore, the garde...",10,July 2022
...,...,...,...,...
5995,Carlton Hotel Singapore,Worth for the money you spend and the location...,8,May 2019
5996,Carlton Hotel Singapore,We had a wonderful stay at the Carlton. We had...,10,May 2019
5997,Carlton Hotel Singapore,Very badly surprised by this hotel which is no...,4,May 2019
5998,Carlton Hotel Singapore,This hotel was awesome. We had a great stay. C...,10,May 2019
5999,Carlton Hotel Singapore,Ive stayed in lots of hotels in Singapore and ...,10,May 2019

In [10]:
xinying_df=pd.read_csv(r'C:\Users\chery\Desktop\python_proj\traveloka_reviews.csv')
xinying_df

,Name,Description,Date Of Stay
0,Marina Bay Sands,Thank you for having me here! I and my husband...,11 Apr 2022
1,Marina Bay Sands,"Got the grand club room - nice room, nice view...",04 Nov 2020
2,Marina Bay Sands,MBS is always the best place to stay while in ...,28 Jan 2020
3,Marina Bay Sands,"The room is really spacious, luxurious bathroo...",26 Jan 2020
4,Marina Bay Sands,Its not worth the money I paid,11 Jan 2020
...,...,...,...
1490,Furama City Centre,Pleasantly surprised my room had a bathtub! Mo...,05 Feb 2022
1491,Furama City Centre,"Location and service quite nice, but hotel int...",05 Feb 2022
1492,Furama City Centre,The hotel and rooms though a bit dated but the...,04 Feb 2022
1493,Furama City Centre,Hotel stay experience is expected. Bed is supe...,03 Feb 2022
1494,Furama City Centre,Such a pleasant stay! The city view was breath...,02 Feb 2022

In [11]:
xinying_df=xinying_df.drop_duplicates()
xinying_df

,Name,Description,Date Of Stay
0,Marina Bay Sands,Thank you for having me here! I and my husband...,11 Apr 2022
1,Marina Bay Sands,"Got the grand club room - nice room, nice view...",04 Nov 2020
2,Marina Bay Sands,MBS is always the best place to stay while in ...,28 Jan 2020
3,Marina Bay Sands,"The room is really spacious, luxurious bathroo...",26 Jan 2020
4,Marina Bay Sands,Its not worth the money I paid,11 Jan 2020
...,...,...,...
1490,Furama City Centre,Pleasantly surprised my room had a bathtub! Mo...,05 Feb 2022
1491,Furama City Centre,"Location and service quite nice, but hotel int...",05 Feb 2022
1492,Furama City Centre,The hotel and rooms though a bit dated but the...,04 Feb 2022
1493,Furama City Centre,Hotel stay experience is expected. Bed is supe...,03 Feb 2022
1494,Furama City Centre,Such a pleasant stay! The city view was breath...,02 Feb 2022

In [12]:
concat_df = pd.concat([codex_df, verno_df,xinying_df])
concat_df=concat_df.sort_values(by=['Hotel Name'])

In [13]:
concat_df

,Hotel Name,Content,Rating,Date of stay,Name,Description,Date Of Stay
10141,Aqueen Hotel Paya Lebar,The stay was comfortable.,10.0,30-Sep-22,NaN,NaN,NaN
10547,Aqueen Hotel Paya Lebar,Pleasent,8.0,28-Aug-15,NaN,NaN,NaN
10545,Aqueen Hotel Paya Lebar,My experience: First we were booked to an insi...,4.0,28-Aug-15,NaN,NaN,NaN
10541,Aqueen Hotel Paya Lebar,"New hotel, great rooms & very reasonably price...",10.0,29-Aug-15,NaN,NaN,NaN
10539,Aqueen Hotel Paya Lebar,"Gem of a hotel, if you don't mind being off th...",8.0,31-Aug-15,NaN,NaN,NaN
...,...,...,...,...,...,...,...
1490,NaN,NaN,NaN,NaN,Furama City Centre,Pleasantly surprised my room had a bathtub! Mo...,05 Feb 2022
1491,NaN,NaN,NaN,NaN,Furama City Centre,"Location and service quite nice, but hotel int...",05 Feb 2022
1492,NaN,NaN,NaN,NaN,Furama City Centre,The hotel and rooms though a bit dated but the...,04 Feb 2022
1493,NaN,NaN,NaN,NaN,Furama City Centre,Hotel stay experience is expected. Bed is supe...,03 Feb 2022
1494,NaN,NaN,NaN,NaN,Furama City Centre,Such a pleasant stay! The city view was breath...,02 Feb 2022

In [14]:
concat_df.to_csv(r'C:\Users\chery\Desktop\python_proj\all_reviews.csv',index=False)

In [15]:
xinying_df_ratings=pd.read_csv(r'C:\Users\chery\Desktop\python_proj\traveloka_hotels.csv')
xinying_df_ratings.rename(columns = {'Name':'Hotel Name'}, inplace = True)
xinying_df_ratings=xinying_df_ratings[['Hotel Name','Cleanliness','Service']]
xinying_df_ratings

                                    Hotel Name  Cleanliness  Service
0                             Marina Bay Sands           10       10
1                      Orchard Hotel Singapore            9        9
2                 YOTEL Singapore Orchard Road           10        9
3          Hilton Singapore Orchard (SG Clean)           10        9
4              Shangri-La Singapore (SG Clean)           10       10
5                The Fullerton Hotel Singapore           10       10
6                           Fairmont Singapore           10       10
7    PARKROYAL COLLECTION Pickering, Singapore            9        9
8   PARKROYAL COLLECTION Marina Bay, Singapore            9        9
9                           M Social Singapore            9        8
10                                 Hotel Royal            9        9
11                                  York Hotel            9        9
12       W Singapore - Sentosa Cove (SG Clean)           10        9
13        Andaz Singapore - a concept by Hyatt           10        9
14                     Carlton Hotel Singapore           10        9
15                          Furama City Centre            9        8
16                Mandarin Oriental, Singapore           10       10
17                Dusit Thani Laguna Singapore            9        9
18                         Goodwood Park Hotel            9        9

In [16]:
verno_df_ratings=pd.read_csv(r'C:\Users\chery\Desktop\python_proj\TAHotels.csv')
verno_df_ratings=verno_df_ratings[['Hotel Name','Cleaniness','Service']]
verno_df_ratings.rename(columns = {'Cleaniness':'Cleanliness'}, inplace = True)

verno_df_ratings

                                    Hotel Name  Cleanliness  Service
0                             Marina Bay Sands          4.5      4.1
1   PARKROYAL COLLECTION Marina Bay, Singapore          4.4      4.3
2                The Fullerton Hotel Singapore          4.7      4.5
3                         Shangri-La Singapore          4.7      4.7
4       The Clan Hotel by Far East Hospitality          4.8      4.8
5                            V Hotel Bencoolen          3.7      3.5
6                              YOTEL Singapore          4.5      4.4
7                 Mandarin Oriental, Singapore          4.7      4.7
8   JEN Singapore Orchardgateway by Shangri-La          4.6      4.3
9                            Furama RiverFront          4.1      4.1
10                     PARKROYAL on Beach Road          4.4      4.3
11                        Park Regis Singapore          4.4      4.4
12                       The Scarlet Singapore          4.5      4.4
13                           Hotel G Singapore          4.4      4.3
14         JEN Singapore Tanglin by Shangri-La          4.5      4.4
15                  Grand Copthorne Waterfront          4.1      4.1
16                     Orchard Hotel Singapore          4.5      4.4
17                        York Hotel Singapore          4.0      3.8
18                                  Hotel Boss          4.0      3.7
19                     Carlton Hotel Singapore          4.3      4.1

In [17]:
codex_df_ratings=pd.read_csv(r'C:\Users\chery\Desktop\python_proj\hotels.csv')
codex_df_ratings=codex_df_ratings.dropna().reset_index(drop=True)
codex_df_ratings=codex_df_ratings[['Hotel Name','Cleanliness','Service']]
codex_df_ratings

                                           Hotel Name  Cleanliness  Service
0             Carlton City Hotel Singapore (SG Clean)          9.1      8.8
1   PARKROYAL COLLECTION Marina Bay, Singapore (SG...          8.5      8.6
2   Crowne Plaza Changi Airport (SG Clean), an IHG...          9.4      9.1
3                 Concorde Hotel Singapore (SG Clean)          8.3      8.4
4             YOTEL Singapore Orchard Road (SG Clean)          9.1      8.7
5            The Fullerton Hotel Singapore (SG Clean)          9.5      9.3
6   Village Hotel Katong by Far East Hospitality (...          9.1      9.1
7   Holiday Inn Singapore Little India, an IHG Hot...          8.4      8.3
8                     Grand Park City Hall (SG Clean)          9.0      8.6
9                   Swissotel The Stamford, Singapore          9.3      9.0
10                      M Social Singapore (SG Clean)          8.6      8.2
11                              Royal Plaza on Scotts          8.7      8.8
12                      Fairmont Singapore (SG Clean)          9.3      9.3
13             PARKROYAL on Kitchener Road, Singapore          7.7      7.6
14                       Hotel NuVe Urbane (SG Clean)          8.5      8.4
15  InterContinental Singapore (SG Clean), an IHG ...          9.3      9.1
16                                     Studio M Hotel          7.0      7.7
17                            Aqueen Hotel Paya Lebar          8.5      8.3
18          Ascott Raffles Place Singapore (SG Clean)          9.0      8.9
19                 Orchard Hotel Singapore (SG Clean)          8.5      8.4

In [18]:
concat_df = pd.concat([codex_df_ratings, verno_df_ratings, xinying_df_ratings])
concat_df=concat_df.sort_values(by=['Hotel Name'])

In [19]:
concat_df

                                           Hotel Name  Cleanliness  Service
13               Andaz Singapore - a concept by Hyatt         10.0      9.0
17                            Aqueen Hotel Paya Lebar          8.5      8.3
18          Ascott Raffles Place Singapore (SG Clean)          9.0      8.9
0             Carlton City Hotel Singapore (SG Clean)          9.1      8.8
14                            Carlton Hotel Singapore         10.0      9.0
19                            Carlton Hotel Singapore          4.3      4.1
3                 Concorde Hotel Singapore (SG Clean)          8.3      8.4
2   Crowne Plaza Changi Airport (SG Clean), an IHG...          9.4      9.1
17                       Dusit Thani Laguna Singapore          9.0      9.0
6                                  Fairmont Singapore         10.0     10.0
12                      Fairmont Singapore (SG Clean)          9.3      9.3
15                                 Furama City Centre          9.0      8.0
9                                   Furama RiverFront          4.1      4.1
18                                Goodwood Park Hotel          9.0      9.0
15                         Grand Copthorne Waterfront          4.1      4.1
8                     Grand Park City Hall (SG Clean)          9.0      8.6
3                 Hilton Singapore Orchard (SG Clean)         10.0      9.0
7   Holiday Inn Singapore Little India, an IHG Hot...          8.4      8.3
18                                         Hotel Boss          4.0      3.7
13                                  Hotel G Singapore          4.4      4.3
14                       Hotel NuVe Urbane (SG Clean)          8.5      8.4
10                                        Hotel Royal          9.0      9.0
15  InterContinental Singapore (SG Clean), an IHG ...          9.3      9.1
8          JEN Singapore Orchardgateway by Shangri-La          4.6      4.3
14                JEN Singapore Tanglin by Shangri-La          4.5      4.4
9                                  M Social Singapore          9.0      8.0
10                      M Social Singapore (SG Clean)          8.6      8.2
7                        Mandarin Oriental, Singapore          4.7      4.7
16                       Mandarin Oriental, Singapore         10.0     10.0
0                                    Marina Bay Sands          4.5      4.1
0                                    Marina Bay Sands         10.0     10.0
1                             Orchard Hotel Singapore          9.0      9.0
16                            Orchard Hotel Singapore          4.5      4.4
19                 Orchard Hotel Singapore (SG Clean)          8.5      8.4
8          PARKROYAL COLLECTION Marina Bay, Singapore          9.0      9.0
1          PARKROYAL COLLECTION Marina Bay, Singapore          4.4      4.3
1   PARKROYAL COLLECTION Marina Bay, Singapore (SG...          8.5      8.6
7           PARKROYAL COLLECTION Pickering, Singapore          9.0      9.0
10                            PARKROYAL on Beach Road          4.4      4.3
13             PARKROYAL on Kitchener Road, Singapore          7.7      7.6
11                               Park Regis Singapore          4.4      4.4
11                              Royal Plaza on Scotts          8.7      8.8
3                                Shangri-La Singapore          4.7      4.7
4                     Shangri-La Singapore (SG Clean)         10.0     10.0
16                                     Studio M Hotel          7.0      7.7
9                   Swissotel The Stamford, Singapore          9.3      9.0
4              The Clan Hotel by Far East Hospitality          4.8      4.8
2                       The Fullerton Hotel Singapore          4.7      4.5
5                       The Fullerton Hotel Singapore         10.0     10.0
5            The Fullerton Hotel Singapore (SG Clean)          9.5      9.3
12                              The Scarlet Singapore          4.5      4.4
5                                   V Hotel Bencoolen          3.7      3.5
6   Village Hotel Katong by Far East Hospitality (...          9.1      9.1
12              W Singapore - Sentosa Cove (SG Clean)         10.0      9.0
6                                     YOTEL Singapore          4.5      4.4
2                        YOTEL Singapore Orchard Road         10.0      9.0
4             YOTEL Singapore Orchard Road (SG Clean)          9.1      8.7
11                                         York Hotel          9.0      9.0
17                               York Hotel Singapore          4.0      3.8

In [20]:
concat_df.to_csv(r'C:\Users\chery\Desktop\python_proj\all_subratings.csv',index=False)